spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pepperfry
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: false
  main:
    banner-mode: off
logging:
  file:
   path: E:\new_projects\microservices\pepperfry-product-service
   name: pepperfry-product-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] - %-5level - %logger{40} - %msg%n"
  level:
    '[com.pepperfry.product]': trace
product:
  defaultCategory: electronic